In [ ]:
import  pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/placement - placement.csv')

In [ ]:
# CHANGEING DATA TYPE
df['cgpa']=df['cgpa'].astype(int)
df

    cgpa  resume_score  placed
0      8          6.52       1
1      6          5.17       0
2      8          8.86       1
3      6          7.27       1
4      7          7.30       1
..   ...           ...     ...
95     6          6.38       0
96     8          7.76       1
97     6          7.78       0
98     8          5.63       1
99     6          6.61       0

[100 rows x 3 columns]

In [ ]:
#changing values
df['cgpa']=df['cgpa'].add(4)
df

    cgpa  resume_score  placed
0     12          6.52       1
1     10          5.17       0
2     12          8.86       1
3     10          7.27       1
4     11          7.30       1
..   ...           ...     ...
95    10          6.38       0
96    12          7.76       1
97    10          7.78       0
98    12          5.63       1
99    10          6.61       0

[100 rows x 3 columns]

In [ ]:
r=df['cgpa'].mean()
r

np.float64(10.47)

In [ ]:
r2=df['cgpa'].median()
r2

10.0

In [ ]:
#filtering the data
#option1
g=df.filter(items=['cgpa','placed'])
g

    cgpa  placed
0     12       1
1     10       0
2     12       1
3     10       1
4     11       1
..   ...     ...
95    10       0
96    12       1
97    10       0
98    12       1
99    10       0

[100 rows x 2 columns]

In [ ]:
#option2
t = df[['cgpa', 'placed']]
t

    cgpa  placed
0      8       1
1      6       0
2      8       1
3      6       1
4      7       1
..   ...     ...
95     6       0
96     8       1
97     6       0
98     8       1
99     6       0

[100 rows x 2 columns]

In [ ]:
## axis =0 means row wise operations
s=df.filter(items=[5,6],axis=0)
s

   cgpa  resume_score  placed
5    12          6.19       1
6     9          7.09       0

In [ ]:
s=df.to_dict() # saving data in dictionary
s

{'cgpa': {0: 12,
  1: 10,
  2: 12,
  3: 10,
  4: 11,
  5: 12,
  6: 9,
  7: 10,
  8: 10,
  9: 11,
  10: 10,
  11: 9,
  12: 10,
  13: 12,
  14: 11,
  15: 12,
  16: 12,
  17: 11,
  18: 9,
  19: 10,
  20: 9,
  21: 10,
  22: 10,
  23: 10,
  24: 12,
  25: 11,
  26: 10,
  27: 9,
  28: 11,
  29: 10,
  30: 11,
  31: 9,
  32: 9,
  33: 12,
  34: 12,
  35: 12,
  36: 12,
  37: 13,
  38: 10,
  39: 11,
  40: 12,
  41: 12,
  42: 10,
  43: 12,
  44: 9,
  45: 12,
  46: 9,
  47: 11,
  48: 9,
  49: 9,
  50: 12,
  51: 10,
  52: 9,
  53: 10,
  54: 9,
  55: 10,
  56: 10,
  57: 10,
  58: 10,
  59: 9,
  60: 9,
  61: 10,
  62: 9,
  63: 12,
  64: 11,
  65: 10,
  66: 12,
  67: 10,
  68: 10,
  69: 12,
  70: 11,
  71: 11,
  72: 11,
  73: 9,
  74: 9,
  75: 10,
  76: 13,
  77: 9,
  78: 9,
  79: 9,
  80: 11,
  81: 10,
  82: 11,
  83: 11,
  84: 9,
  85: 10,
  86: 10,
  87: 9,
  88: 12,
  89: 9,
  90: 9,
  91: 12,
  92: 9,
  93: 13,
  94: 12,
  95: 10,
  96: 12,
  97: 10,
  98: 12,
  99: 10},
 'resume_score': {0: 6.52,
  1: 5.17,
  2: 8.86,
  3: 7.27,
  4: 7.3,
  5: 6.19,
  6: 7.09,
  7: 6.29,
  8: 6.71,
  9: 7.12,
  10: 6.35,
  11: 6.54,
  12: 7.01,
  13: 5.09,
  14: 6.25,
  15: 5.93,
  16: 7.64,
  17: 8.71,
  18: 5.88,
  19: 8.11,
  20: 8.06,
  21: 7.64,
  22: 5.77,
  23: 7.13,
  24: 6.18,
  25: 5.68,
  26: 6.47,
  27: 6.15,
  28: 7.67,
  29: 7.3,
  30: 7.15,
  31: 7.02,
  32: 7.96,
  33: 7.73,
  34: 7.19,
  35: 7.48,
  36: 7.56,
  37: 8.21,
  38: 8.72,
  39: 6.19,
  40: 5.32,
  41: 5.15,
  42: 6.91,
  43: 7.95,
  44: 5.92,
  45: 5.44,
  46: 5.21,
  47: 8.14,
  48: 6.57,
  49: 6.73,
  50: 6.74,
  51: 7.39,
  52: 7.5,
  53: 7.16,
  54: 7.18,
  55: 6.87,
  56: 6.43,
  57: 7.21,
  58: 7.37,
  59: 7.57,
  60: 6.64,
  61: 7.96,
  62: 8.43,
  63: 7.58,
  64: 8.09,
  65: 8.75,
  66: 8.02,
  67: 6.81,
  68: 7.49,
  69: 9.06,
  70: 7.41,
  71: 8.22,
  72: 7.98,
  73: 6.48,
  74: 7.36,
  75: 7.94,
  76: 5.5,
  77: 6.92,
  78: 5.66,
  79: 7.28,
  80: 7.7,
  81: 6.72,
  82: 6.06,
  83: 8.08,
  84: 6.49,
  85: 5.46,
  86: 5.76,
  87: 5.05,
  88: 6.07,
  89: 7.49,
  90: 5.56,
  91: 6.3,
  92: 6.18,
  93: 7.39,
  94: 4.95,
  95: 6.38,
  96: 7.76,
  97: 7.78,
  98: 5.63,
  99: 6.61},
 'placed': {0: 1,
  1: 0,
  2: 1,
  3: 1,
  4: 1,
  5: 1,
  6: 0,
  7: 0,
  8: 0,
  9: 1,
  10: 0,
  11: 0,
  12: 0,
  13: 1,
  14: 1,
  15: 1,
  16: 1,
  17: 1,
  18: 0,
  19: 1,
  20: 0,
  21: 0,
  22: 0,
  23: 0,
  24: 1,
  25: 1,
  26: 0,
  27: 0,
  28: 1,
  29: 0,
  30: 1,
  31: 0,
  32: 0,
  33: 1,
  34: 1,
  35: 1,
  36: 1,
  37: 1,
  38: 0,
  39: 1,
  40: 1,
  41: 1,
  42: 1,
  43: 1,
  44: 0,
  45: 1,
  46: 0,
  47: 1,
  48: 0,
  49: 0,
  50: 1,
  51: 0,
  52: 0,
  53: 0,
  54: 0,
  55: 1,
  56: 0,
  57: 0,
  58: 0,
  59: 0,
  60: 0,
  61: 1,
  62: 0,
  63: 1,
  64: 1,
  65: 0,
  66: 1,
  67: 1,
  68: 0,
  69: 1,
  70: 1,
  71: 1,
  72: 1,
  73: 0,
  74: 0,
  75: 1,
  76: 1,
  77: 0,
  78: 0,
  79: 0,
  80: 1,
  81: 0,
  82: 1,
  83: 1,
  84: 0,
  85: 0,
  86: 0,
  87: 0,
  88: 1,
  89: 0,
  90: 0,
  91: 1,
  92: 0,
  93: 1,
  94: 1,
  95: 0,
  96: 1,
  97: 0,
  98: 1,
  99: 0}}

In [ ]:
q=df.to_string() # into string
q

'    cgpa  resume_score  placed\n0     12          6.52       1\n1     10          5.17       0\n2     12          8.86       1\n3     10          7.27       1\n4     11          7.30       1\n5     12          6.19       1\n6      9          7.09       0\n7     10          6.29       0\n8     10          6.71       0\n9     11          7.12       1\n10    10          6.35       0\n11     9          6.54       0\n12    10          7.01       0\n13    12          5.09       1\n14    11          6.25       1\n15    12          5.93       1\n16    12          7.64       1\n17    11          8.71       1\n18     9          5.88       0\n19    10          8.11       1\n20     9          8.06       0\n21    10          7.64       0\n22    10          5.77       0\n23    10          7.13       0\n24    12          6.18       1\n25    11          5.68       1\n26    10          6.47       0\n27     9          6.15       0\n28    11          7.67       1\n29    10          7.30       0\n30    11          7.15       1\n31     9          7.02       0\n32     9          7.96       0\n33    12          7.73       1\n34    12          7.19       1\n35    12          7.48       1\n36    12          7.56       1\n37    13          8.21       1\n38    10          8.72       0\n39    11          6.19       1\n40    12          5.32       1\n41    12          5.15       1\n42    10          6.91       1\n43    12          7.95       1\n44     9          5.92       0\n45    12          5.44       1\n46     9          5.21       0\n47    11          8.14       1\n48     9          6.57       0\n49     9          6.73       0\n50    12          6.74       1\n51    10          7.39       0\n52     9          7.50       0\n53    10          7.16       0\n54     9          7.18       0\n55    10          6.87       1\n56    10          6.43       0\n57    10          7.21       0\n58    10          7.37       0\n59     9          7.57       0\n60     9          6.64       0\n61    10          7.96       1\n62     9          8.43       0\n63    12          7.58       1\n64    11          8.09       1\n65    10          8.75       0\n66    12          8.02       1\n67    10          6.81       1\n68    10          7.49       0\n69    12          9.06       1\n70    11          7.41       1\n71    11          8.22       1\n72    11          7.98       1\n73     9          6.48       0\n74     9          7.36       0\n75    10          7.94       1\n76    13          5.50       1\n77     9          6.92       0\n78     9          5.66       0\n79     9          7.28       0\n80    11          7.70       1\n81    10          6.72       0\n82    11          6.06       1\n83    11          8.08       1\n84     9          6.49       0\n85    10          5.46       0\n86    10          5.76       0\n87     9          5.05       0\n88    12          6.07       1\n89     9          7.49       0\n90     9          5.56       0\n91    12          6.30       1\n92     9          6.18       0\n93    13          7.39       1\n94    12          4.95       1\n95    10          6.38       0\n96    12          7.76       1\n97    10          7.78       0\n98    12          5.63       1\n99    10          6.61       0'

In [ ]:
idx=df.columns # know colums of dataframe
idx

Index(['cgpa', 'resume_score', 'placed'], dtype='object')

In [ ]:
label=df.columns[0] # index of columns
label

'cgpa'

In [ ]:
q=df.columns.values # array of colums name
q

array(['cgpa', 'resume_score', 'placed'], dtype=object)

In [ ]:
df['cgpa']=df['cgpa'].subtract(4)

In [ ]:
df['half']=df['cgpa'].where(df['cgpa']>7,other=0)
df.head(6)

   cgpa  resume_score  placed  half
0     8          6.52       1     8
1     6          5.17       0     0
2     8          8.86       1     8
3     6          7.27       1     0
4     7          7.30       1     0
5     8          6.19       1     8

In [ ]:
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [ ]:
df.tail()

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [ ]:
top_left_corner=df.iloc[:5,:3]
top_left_corner

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [ ]:
top_left_corner_loc=df.loc[:5,['cgpa','placed']]
top_left_corner_loc

   cgpa  placed
0  8.14       1
1  6.17       0
2  8.27       1
3  6.88       1
4  7.52       1
5  8.77       1

In [ ]:
df.axes

[RangeIndex(start=0, stop=100, step=1),
 Index(['cgpa', 'resume_score', 'placed'], dtype='object')]

In [ ]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [ ]:
df=df.dropna()

In [ ]:
i=df.ndim
i

2

In [ ]:
t=df.shape
t

(100, 3)

In [ ]:
print(df.shape[0]) # rows
print(df.shape[1]) # columns

100
3

In [ ]:
d=df.size
d

300

In [ ]:
a=df.values # get numpy array
a

In [ ]:
df=df.copy

In [ ]:
df=pd.read_csv('/content/placement - placement.csv')
p=df.sort_values(by = 'resume_score')
p

    cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0
..   ...           ...     ...
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

[100 rows x 3 columns]

data->
1.numerical->continous->we can divide further
eg salary weight
2.categorocal->descrete->we canot divide further
eg gender number of employees

In [ ]:
# tips dataset
# categorical clum = numerical colum using map
# rows,column loc,iloc,1 colum sort

In [ ]:
tp=pd.read_csv('/content/tips - tips.csv')

In [ ]:
tp.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
#rows between 11 to 13
#t1=tp.filter(items=[11,13],axis=0)
t1=tp.iloc[11:14]
t1

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4

In [ ]:
p=tp.filter(items=['tip','sex','day'])
p

      tip     sex   day
0    1.01  Female   Sun
1    1.66    Male   Sun
2    3.50    Male   Sun
3    3.31    Male   Sun
4    3.61  Female   Sun
..    ...     ...   ...
239  5.92    Male   Sat
240  2.00  Female   Sat
241  2.00    Male   Sat
242  1.75    Male   Sat
243  3.00  Female  Thur

[244 rows x 3 columns]

In [ ]:
#rename 2 columns
p=p.rename(columns={'tip':'tip_amount','sex':'gender'})
p

     tip_amount  gender   day
0          1.01  Female   Sun
1          1.66    Male   Sun
2          3.50    Male   Sun
3          3.31    Male   Sun
4          3.61  Female   Sun
..          ...     ...   ...
239        5.92    Male   Sat
240        2.00  Female   Sat
241        2.00    Male   Sat
242        1.75    Male   Sat
243        3.00  Female  Thur

[244 rows x 3 columns]

In [ ]:
tp['male_customer']=tp['sex'].where(tp['sex']=='Male',other=0)
tp

     total_bill   tip     sex smoker   day    time  size male_customer
0            16  1.01  Female     No   Sun  Dinner     2             0
1            10  1.66    Male     No   Sun  Dinner     3          Male
2            21  3.50    Male     No   Sun  Dinner     3          Male
3            23  3.31    Male     No   Sun  Dinner     2          Male
4            24  3.61  Female     No   Sun  Dinner     4             0
..          ...   ...     ...    ...   ...     ...   ...           ...
239          29  5.92    Male     No   Sat  Dinner     3          Male
240          27  2.00  Female    Yes   Sat  Dinner     2             0
241          22  2.00    Male    Yes   Sat  Dinner     2          Male
242          17  1.75    Male     No   Sat  Dinner     2          Male
243          18  3.00  Female     No  Thur  Dinner     2             0

[244 rows x 8 columns]

In [ ]:
#datatype of each colums and top 6 data ,export to csv,excel
p=tp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   total_bill     244 non-null    int64
 1   tip            244 non-null    float64
 2   sex            244 non-null    object
 3   smoker         244 non-null    object
 4   day            244 non-null    object
 5   time           244 non-null    object
 6   size           244 non-null    int64
 7   male_customer  244 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 15.4+ KB

In [ ]:
tp.head(6)

   total_bill   tip     sex smoker  day    time  size male_customer
0          16  1.01  Female     No  Sun  Dinner     2             0
1          10  1.66    Male     No  Sun  Dinner     3          Male
2          21  3.50    Male     No  Sun  Dinner     3          Male
3          23  3.31    Male     No  Sun  Dinner     2          Male
4          24  3.61  Female     No  Sun  Dinner     4             0
5          25  4.71    Male     No  Sun  Dinner     4          Male

In [ ]:
p=tp.to_csv('tips11.csv')
q=tp.to_excel('tips11.xlsx')

In [ ]:
#totalbill=integer
tp['total_bill']=tp['total_bill'].astype(int)
tp

     total_bill   tip     sex smoker   day    time  size
0            16  1.01  Female     No   Sun  Dinner     2
1            10  1.66    Male     No   Sun  Dinner     3
2            21  3.50    Male     No   Sun  Dinner     3
3            23  3.31    Male     No   Sun  Dinner     2
4            24  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239          29  5.92    Male     No   Sat  Dinner     3
240          27  2.00  Female    Yes   Sat  Dinner     2
241          22  2.00    Male    Yes   Sat  Dinner     2
242          17  1.75    Male     No   Sat  Dinner     2
243          18  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
tp.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
tp.dtypes

total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object

In [ ]:
tp.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
tp['sex']=tp['sex'].map({'Female':0,'Male':1})

In [ ]:
tp.head()

   total_bill   tip  sex smoker  day    time  size
0       16.99  1.01    0     No  Sun  Dinner     2
1       10.34  1.66    1     No  Sun  Dinner     3
2       21.01  3.50    1     No  Sun  Dinner     3
3       23.68  3.31    1     No  Sun  Dinner     2
4       24.59  3.61    0     No  Sun  Dinner     4

In [ ]:
top_left_corner_tip=tp.iloc[:5,:3]
top_left_corner_tip

   total_bill   tip  sex
0       16.99  1.01    0
1       10.34  1.66    1
2       21.01  3.50    1
3       23.68  3.31    1
4       24.59  3.61    0

In [ ]:
top_left_corner_tip_loc1=tp.loc[:5,['tip','sex']]
top_left_corner_tip_loc1

    tip  sex
0  1.01    0
1  1.66    1
2  3.50    1
3  3.31    1
4  3.61    0
5  4.71    1

In [ ]:
tp.sort_values(by='tip')

     total_bill    tip  sex smoker   day    time  size
92         5.75   1.00    0    Yes   Fri  Dinner     2
111        7.25   1.00    0     No   Sat  Dinner     1
67         3.07   1.00    0    Yes   Sat  Dinner     1
236       12.60   1.00    1    Yes   Sat  Dinner     2
0         16.99   1.01    0     No   Sun  Dinner     2
..          ...    ...  ...    ...   ...     ...   ...
141       34.30   6.70    1     No  Thur   Lunch     6
59        48.27   6.73    1     No   Sat  Dinner     4
23        39.42   7.58    1     No   Sat  Dinner     4
212       48.33   9.00    1     No   Sat  Dinner     4
170       50.81  10.00    1    Yes   Sat  Dinner     3

[244 rows x 7 columns]

In [ ]:
tp.head()

   total_bill   tip  sex smoker  day    time  size
0       16.99  1.01    0     No  Sun  Dinner     2
1       10.34  1.66    1     No  Sun  Dinner     3
2       21.01  3.50    1     No  Sun  Dinner     3
3       23.68  3.31    1     No  Sun  Dinner     2
4       24.59  3.61    0     No  Sun  Dinner     4

In [ ]:
tp['smoker']=tp['smoker'].map({'No':0,'Yes':1})

In [ ]:
#check unique values of day
tp['day'].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [ ]:
tp['day']=tp['day'].map({'Thur':0,'Fri':1,'Sat':2,'Sun':3})

In [ ]:
tp['time'].unique()

array(['Dinner', 'Lunch'], dtype=object)

In [ ]:
tp['time']=tp['time'].map({'Lunch':0,'Dinner':1})

In [ ]:
tp

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    3     1     2
1         10.34  1.66    1       0    3     1     3
2         21.01  3.50    1       0    3     1     3
3         23.68  3.31    1       0    3     1     2
4         24.59  3.61    0       0    3     1     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    2     1     3
240       27.18  2.00    0       1    2     1     2
241       22.67  2.00    1       1    2     1     2
242       17.82  1.75    1       0    2     1     2
243       18.78  3.00    0       0    0     1     2

[244 rows x 7 columns]